'use strict';
module.exports = function (ctx) {
  const { c, layout, util, instruments, content } = ctx;
  const { html, raw, num } = util;
  const q = (s) => ctx.quote(s) || {};
  const pages = [];
  const add = (path, title, description, body, noindex) => { content.searchablePages.push({ title, path, kicker: 'Werkzeuge', description }); pages.push({ path, html: layout.page({ title, description, path, body, section: 'werkzeuge', noindex }) }); };
  const icon = (d) => raw(`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`);
  const field = (name, label, value, suffix, hint, attrs = '') => html`<div class="field"><label for="f-${name}">${label}</label><div class="control"><input id="f-${name}" name="${name}" type="text" inputmode="decimal" value="${value}" ${raw(attrs)}>${suffix ? html`<span class="suffix">${suffix}</span>` : ''}</div>${hint ? html`<span class="hint">${hint}</span>` : ''}</div>`;

  const tools = [
    { slug: 'zinseszinsrechner', title: 'Zinseszinsrechner', short: 'Wie aus Startkapital und Sparrate über die Jahre Vermögen wird.', icon: icon('<path d="M3 17 9 11l4 4 8-8"/><path d="M14 7h7v7"/>'),
      lead: 'Berechnen Sie, wie sich ein Startkapital mit monatlichen Einzahlungen bei einer angenommenen Rendite entwickelt – und welcher Anteil des Endkapitals aus Zinsen und Kursgewinnen stammt.',
      form: html`${field('start', 'Startkapital', '10.000', '€')}${field('rate', 'Monatliche Sparrate', '200', '€')}${field('interest', 'Rendite pro Jahr', '6', '%', 'Breit gestreute Aktienindizes brachten langfristig 6–8 % nominal.')}${field('years', 'Laufzeit', '20', 'Jahre')}`,
      text: `<h2>So funktioniert der Zinseszins</h2><p>Erträge werden nicht ausgezahlt, sondern wieder angelegt und erwirtschaften selbst Erträge. Das Kapital wächst exponentiell: In den ersten Jahren dominieren die Einzahlungen, später die Erträge. Bei 6 % verdoppelt sich ein Betrag etwa alle zwölf Jahre („72er-Regel“: 72 geteilt durch den Zinssatz).</p><h2>Formel</h2><p>Endkapital = Startkapital × (1 + r)<sup>n</sup> + Sparrate × Σ (1 + r<sub>m</sub>)<sup>k</sup>, wobei r die Jahresrendite, r<sub>m</sub> die daraus abgeleitete Monatsrendite und n die Jahre sind. Der Rechner verzinst monatlich.</p><h2>Was der Rechner nicht berücksichtigt</h2><ul><li>Steuern: Auf Erträge fallen 26,375 % Abgeltungsteuer an, oberhalb des Sparer-Pauschbetrags von 1.000 € pro Jahr.</li><li>Inflation: 2 % Inflation halbieren die Kaufkraft in etwa 35 Jahren. Nutzen Sie den <a href="/werkzeuge/inflationsrechner">Inflationsrechner</a>.</li><li>Schwankungen: Die Rendite ist ein Durchschnitt. Reale Verläufe haben Jahre mit −30 % und +30 %.</li></ul>` },
    { slug: 'sparplanrechner', title: 'Sparplanrechner', short: 'Depotwert eines ETF-Sparplans nach Kosten.', icon: icon('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 15l3-3 3 2 4-5"/>'),
      lead: 'Wie viel ein monatlicher ETF-Sparplan nach 10, 20 oder 30 Jahren wert sein kann – mit Berücksichtigung der laufenden Fondskosten (TER).',
      form: html`${field('rate', 'Monatliche Sparrate', '100', '€')}${field('years', 'Laufzeit', '25', 'Jahre')}${field('return', 'Erwartete Rendite pro Jahr (vor Kosten)', '7', '%')}${field('cost', 'Laufende Kosten (TER)', '0,2', '% p. a.', 'Welt-ETFs: 0,1–0,25 %. Aktive Fonds: 1,5 % und mehr.')}`,
      text: `<h2>Warum Kosten so stark wirken</h2><p>Die TER wird jedes Jahr vom Fondsvermögen abgezogen – also auch von den bereits erzielten Gewinnen. Ein Prozentpunkt mehr Kosten kostet über 30 Jahre rund ein Fünftel des Endvermögens. Vergleichen Sie im Rechner 0,2 % mit 1,5 %.</p><h2>Realistische Annahmen</h2><p>Der MSCI World brachte seit 1970 im Durchschnitt rund 7 % pro Jahr in Euro vor Kosten – mit Dekaden zwischen 0 % und 12 %. Für Planungen ist eine Spanne (5 bis 8 %) ehrlicher als eine Zahl.</p><h2>Cost-Average-Effekt</h2><p>Mit festem Betrag kaufen Sie bei niedrigen Kursen mehr Anteile und bei hohen weniger. Das senkt nicht die erwartete Rendite, macht den Einstieg aber unabhängig vom Timing. Mehr im Ratgeber <a href="/wissen/etf-sparplan">ETF & Sparplan</a>.</p>` },
    { slug: 'renditerechner', title: 'Renditerechner', short: 'Gewinn und Jahresrendite eines Aktienkaufs nach Kosten.', icon: icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/>'),
      lead: 'Gesamt- und Jahresrendite eines Wertpapierkaufs aus Kauf- und Verkaufskurs, Stückzahl, Gebühren und Haltedauer.',
      form: html`${field('buy', 'Kaufkurs', '85,00', '€')}${field('sell', 'Verkaufskurs', '112,50', '€')}${field('qty', 'Stückzahl', '50', 'Stück')}${field('fees', 'Gebühren gesamt (Kauf + Verkauf)', '9,80', '€')}${field('hold', 'Haltedauer', '2,5', 'Jahre')}`,
      text: `<h2>Gesamtrendite und annualisierte Rendite</h2><p>Die Gesamtrendite setzt den Gewinn ins Verhältnis zum Einsatz. Die annualisierte Rendite rechnet sie auf ein Jahr um, damit sich Anlagen unterschiedlicher Dauer vergleichen lassen: (Endwert / Einsatz)<sup>1/Jahre</sup> − 1.</p><h2>Steuern</h2><p>Kursgewinne unterliegen der Abgeltungsteuer von 25 % plus Solidaritätszuschlag (26,375 %). Der Sparer-Pauschbetrag von 1.000 € pro Jahr bleibt frei. Verluste aus Aktien lassen sich nur mit Aktiengewinnen verrechnen. Details: <a href="/wissen/steuern">Steuern auf Kapitalerträge</a>.</p><h2>Dividenden</h2><p>Dieser Rechner betrachtet nur den Kursgewinn. Ausschüttungen berechnen Sie mit dem <a href="/werkzeuge/dividendenrechner">Dividendenrechner</a>.</p>` },
    { slug: 'dividendenrechner', title: 'Dividendenrechner', short: 'Dividendenrendite, Netto-Ausschüttung und Summe über Jahre.', icon: icon('<path d="M12 3v18M7 8h7a3 3 0 0 1 0 6H9a3 3 0 0 0 0 6h8"/>'),
      lead: `Dividendenrendite aus Kurs und Ausschüttung, Nettobetrag nach Steuern und die Summe über mehrere Jahre bei angenommenem Dividendenwachstum. Vorbelegt mit den Werten der Allianz-Aktie (${num(q('allianz').price)} €, Rendite ${num(q('allianz').dividendYield, 2)} %).`,
      form: html`${field('price', 'Aktienkurs', num(q('allianz').price), '€')}${field('div', 'Dividende je Aktie (pro Jahr)', num(q('allianz').price * q('allianz').dividendYield / 100), '€')}${field('shares', 'Anzahl Aktien', '40', 'Stück')}${field('growth', 'Dividendenwachstum pro Jahr', '5', '%')}${field('years', 'Betrachtungszeitraum', '10', 'Jahre')}`,
      text: `<h2>Dividendenrendite</h2><p>Dividende je Aktie geteilt durch Kurs. Im DAX liegt sie im Schnitt bei 2,5 bis 3,5 %. Die aktuellen Renditen aller Werte finden Sie im <a href="/termine/dividenden">Dividendenkalender</a>.</p><h2>Steuern auf Dividenden</h2><p>Deutsche Dividenden: 26,375 % Abgeltungsteuer (inkl. Soli), automatisch abgeführt, bis 1.000 € pro Jahr frei. Ausländische Dividenden: zusätzlich Quellensteuer des Herkunftslandes, davon 15 % anrechenbar.</p><h2>Dividendenwachstum</h2><p>Unternehmen wie Allianz oder Münchener Rück haben ihre Dividende über Jahre erhöht. Bei 5 % Wachstum verdoppelt sich die Ausschüttung in gut 14 Jahren – die persönliche Rendite auf den ursprünglichen Kaufpreis („Yield on Cost“) steigt entsprechend.</p>` },
    { slug: 'waehrungsrechner', title: 'Währungsrechner', short: 'Euro in US-Dollar, Pfund, Franken, Yen umrechnen.', icon: icon('<path d="M4 12h16M4 12l4-4M4 12l4 4M20 12l-4-4M20 12l-4 4"/>'),
      lead: `Beträge zwischen Euro und Fremdwährung umrechnen – mit dem aktuellen Referenzkurs (EUR/USD ${num(q('eur-usd').price, 4)}, ${layout.asOfLabel}) oder einem eigenen Kurs.`,
      form: html`${field('amount', 'Betrag', '1.000', '')}<div class="field"><label for="f-dir">Richtung</label><div class="control"><select id="f-dir" name="dir"><option value="eur2">Euro → Fremdwährung</option><option value="2eur">Fremdwährung → Euro</option></select></div></div>${field('rate', 'Wechselkurs (1 € in Fremdwährung)', num(q('eur-usd').price, 4), '', 'Referenzkurse: USD ' + num(q('eur-usd').price, 4) + ' · GBP ' + num(q('eur-gbp').price, 4) + ' · CHF ' + num(q('eur-chf').price, 4) + ' · JPY ' + num(q('eur-jpy').price, 2))}`,
      text: `<h2>Referenzkurs und tatsächlicher Kurs</h2><p>Der hier verwendete Interbankenkurs ist der Mittelkurs am Devisenmarkt. Banken und Wechselstuben rechnen mit einem Aufschlag von 1 bis 3 %, Kartenzahlungen im Ausland oft mit 1 bis 2 % plus Gebühr. Für 1.000 € erhalten Sie also in der Praxis 10 bis 30 US-Dollar weniger als der Rechner ausweist.</p><h2>Aktuelle Kurse</h2><p>Alle Währungspaare mit Chart und Kreuzkursen finden Sie unter <a href="/devisen">Devisen</a>.</p>` },
    { slug: 'positionsgroessenrechner', title: 'Positionsgrößenrechner', short: 'Wie viele Stücke bei festem Risiko und Stop-Loss.', icon: icon('<path d="M12 2 3 7v10l9 5 9-5V7z"/><path d="M12 12v10M3 7l9 5 9-5"/>'),
      lead: 'Bestimmen Sie die Stückzahl so, dass ein Fehltrade nur einen festgelegten Prozentsatz Ihres Depots kostet – die wichtigste Regel des Risikomanagements.',
      form: html`${field('capital', 'Depotwert', '25.000', '€')}${field('risk', 'Risiko pro Position', '1', '% des Depots', 'Übliche Werte: 0,5 bis 2 %.')}${field('entry', 'Einstiegskurs', num(q('sap').price), '€')}${field('stop', 'Stop-Loss-Kurs', num(q('sap').price * 0.93), '€')}`,
      text: `<h2>Die 1-%-Regel</h2><p>Riskieren Sie pro Trade höchstens 1 bis 2 % Ihres Depots. Bei 25.000 € Depot und 1 % sind das 250 €. Liegt der Stop 7 % unter dem Einstieg, dürfen Sie 250 € / (7 % × Kurs) Stücke kaufen. Zehn Fehltrades in Folge kosten dann 10 % – unangenehm, aber kein Ruin.</p><h2>Stop-Loss richtig setzen</h2><p>Der Stop gehört unter eine charttechnische Marke (Unterstützung, gleitender Durchschnitt), nicht auf einen runden Betrag. Wie man Marken bestimmt, steht im Ratgeber <a href="/wissen/chartanalyse">Chartanalyse</a>. Beachten Sie: Ein Stop-Loss garantiert bei Kurslücken keinen Ausführungspreis.</p>` },
    { slug: 'inflationsrechner', title: 'Inflationsrechner', short: 'Kaufkraft eines Betrags in x Jahren.', icon: icon('<path d="M3 3v18h18"/><path d="M7 15l4-6 4 3 5-7"/>'),
      lead: 'Was ein Geldbetrag in einigen Jahren noch wert ist – und wie viel Sie dann brauchen, um dieselbe Kaufkraft zu haben.',
      form: html`${field('amount', 'Betrag heute', '50.000', '€')}${field('inflation', 'Inflationsrate pro Jahr', '2', '%', 'EZB-Ziel: 2 %. Durchschnitt Deutschland 1991–2025: rund 2 %.')}${field('years', 'Zeitraum', '20', 'Jahre')}`,
      text: `<h2>Warum das wichtig ist</h2><p>Inflation ist die unsichtbare Gebühr auf Bargeld und Sparbuch. Bei 2 % verliert Geld in 35 Jahren die Hälfte seiner Kaufkraft, bei 4 % bereits in 18 Jahren. Wer für die Rente spart, muss deshalb in Kaufkraft rechnen, nicht in Euro.</p><h2>Realrendite</h2><p>Die Realrendite ist die Nominalrendite minus Inflation. Tagesgeld mit 2,5 % bei 2,5 % Inflation bringt real null. Aktien mit 7 % nominal bringen real rund 5 %. Wie Sie die Inflationsrate richtig lesen, erklärt <a href="/artikel/inflation-verbraucherpreise-richtig-lesen">dieser Beitrag</a>.</p>` },
  ];

  // Hub
  {
    const body = html`<div class="container page">
      ${c.breadcrumb([['Werkzeuge', '/werkzeuge']])}
      ${c.pageHead({ kicker: 'Werkzeuge', title: 'Rechner & Werkzeuge', lead: 'Sieben Rechner für die wichtigsten Anlegerfragen – Zinseszins, Sparplan, Rendite, Dividende, Währung, Positionsgröße, Inflation. Alle Berechnungen laufen in Ihrem Browser, es werden keine Daten übertragen.' })}
      <div class="tool-grid">${tools.map(t => html`<a class="tool-card" href="/werkzeuge/${t.slug}"><span class="icon">${t.icon}</span><h3>${t.title}</h3><p>${t.short}</p></a>`)}<a class="tool-card" href="/merkliste"><span class="icon">${raw(layout.icons.star)}</span><h3>Merkliste</h3><p>Ihre beobachteten Aktien, Indizes und Rohstoffe auf einer Seite – gespeichert nur in Ihrem Browser.</p></a></div>
      <div class="grid-2" style="margin-top:32px"><section class="card">${c.sectionTitle('Passende Ratgeber')}<ul class="side-list">${content.guides.slice(0, 5).map(g => html`<li><a href="/wissen/${g.slug}"><span class="kicker">${g.kicker}</span><span>${g.title}</span></a></li>`)}</ul></section><section class="card">${c.sectionTitle('Hinweis')}<p class="small">Die Rechner arbeiten mit vereinfachten Annahmen (konstante Rendite, monatliche Verzinsung, keine Steuern, sofern nicht angegeben). Sie ersetzen keine Finanz- oder Steuerberatung. Zahlen mit Komma oder Punkt als Dezimaltrennzeichen werden akzeptiert.</p></section></div>
    </div>`;
    add('/werkzeuge', 'Rechner & Werkzeuge', 'Zinseszins-, Sparplan-, Rendite-, Dividenden-, Währungs-, Positionsgrößen- und Inflationsrechner.', body);
  }
  for (const t of tools) {
    const body = html`<div class="container page">
      ${c.breadcrumb([['Werkzeuge', '/werkzeuge'], [t.title, `/werkzeuge/${t.slug}`]])}
      ${c.pageHead({ kicker: 'Rechner', title: t.title, lead: t.lead })}
      <form class="calc card" data-calc="${t.slug.replace('rechner', '').replace('positionsgroessen', 'position').replace('waehrungs', 'waehrung').replace('inflations', 'inflation').replace('dividenden', 'dividende').replace('zinseszins', 'zinseszins').replace('sparplan', 'sparplan').replace('rendite', 'rendite')}" novalidate><div class="calc-form">${t.form}<button class="btn btn-dark" type="submit">Berechnen</button></div><div class="calc-out" data-calc-out aria-live="polite"></div></form>
      <div class="layout no-sticky" style="margin-top:28px"><div class="prose card">${raw(c.wrapTables(t.text))}</div><aside>${c.sideCard('Weitere Rechner', html`<ul class="side-links">${tools.filter(x => x !== t).map(x => html`<li><a href="/werkzeuge/${x.slug}">${x.icon}${x.title}</a></li>`)}</ul>`)}${c.newsletterBox({ compact: true })}</aside></div>
    </div>`;
    add(`/werkzeuge/${t.slug}`, t.title, t.lead, body);
  }

  // Merkliste
  {
    const popular = ['dax', 'sap', 'rheinmetall', 'siemens-energy', 'gold', 'bitcoin', 'eur-usd', 'allianz'].map(s => instruments.bySlug[s]);
    const body = html`<div class="container page" data-watchlist-page>
      ${c.breadcrumb([['Werkzeuge', '/werkzeuge'], ['Merkliste', '/merkliste']])}
      ${c.pageHead({ kicker: 'Werkzeuge', title: 'Meine Merkliste', lead: 'Aktien, Indizes, Rohstoffe und Währungen, die Sie beobachten möchten – mit dem Stern-Symbol auf jeder Kursseite hinzufügen. Die Liste wird ausschließlich lokal in Ihrem Browser gespeichert.' })}
      <div class="card" data-watchlist-table hidden><div class="section-title"><h2>Beobachtete Werte</h2><button class="btn btn-ghost btn-sm" type="button" data-watchlist-clear>Liste leeren</button></div><div class="table-wrap"><table class="quote-table"><thead><tr><th>Name</th><th class="num">Kurs</th><th class="num">±%</th><th class="num">YTD</th><th></th></tr></thead><tbody data-watchlist-rows></tbody></table></div><p class="small muted" style="margin-top:8px">${layout.asOfLabel}.</p></div>
      <div data-watchlist-empty><div class="empty" style="margin-bottom:24px"><p><strong>Ihre Merkliste ist noch leer.</strong></p><p>Klicken Sie auf einer Kursseite oder in der Tabelle unten auf das Stern-Symbol, um Werte hinzuzufügen.</p></div><section class="card">${c.sectionTitle('Häufig beobachtet')}${c.quoteTable(popular, { cols: ['price', 'change', 'ytd', 'watch'], sortable: false })}</section></div>
      <p class="small muted" style="margin-top:20px">Datenschutz: Die Merkliste liegt im lokalen Speicher Ihres Browsers (localStorage) und wird nicht an uns übertragen. Beim Löschen der Browserdaten geht sie verloren. Details unter <a href="/cookie-einstellungen">Cookie-Einstellungen</a>.</p>
    </div>`;
    add('/merkliste', 'Merkliste', 'Ihre beobachteten Werte auf einer Seite, gespeichert nur in Ihrem Browser.', body, true);
  }
  return pages;
};
